// Code generated by hertz generator.

package social

import (
	"context"

	social "github.com/ACaiCat/tiktok-go/biz/model/social"
	mw "github.com/ACaiCat/tiktok-go/biz/mw/auth"
	"github.com/ACaiCat/tiktok-go/biz/pack"
	service "github.com/ACaiCat/tiktok-go/biz/service/social"
	"github.com/ACaiCat/tiktok-go/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
)

// Follow .
// @router /relation/action [POST]
func Follow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		return
	}

	userID := mw.GetUserID(c)

	err = service.NewSocialService().FollowAction(&req, userID)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespFollow(c)

}

// ListFollowing .
// @router /following/list [GET]
func ListFollowing(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFollowingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		return
	}

	users, total, err := service.NewSocialService().ListFollowing(&req)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespListFollowing(c, users, total)
}

// ListFollower .
// @router /follower/list [GET]
func ListFollower(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFollowerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		return
	}

	users, total, err := service.NewSocialService().ListFollower(&req)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespListFollower(c, users, total)
}

// ListFriend .
// @router /friends/list [GET]
func ListFriend(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.ListFriendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		return
	}

	userID := mw.GetUserID(c)

	users, total, err := service.NewSocialService().ListFriend(&req, userID)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespListFriend(c, users, total)
}
