coverage:
  range: 60..100
  precision: 2

  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "cmd"
  - "config"
  - "docs"
  - "idl"

  - "**/router/**"
  - "**/pack/**"
  - "**/model/**"
  - "**/query/**"

  - "*.pb.go"
  - "*.pb.validate.go"
  - "*_gen.go"
  - "*_generated.go"

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
