// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package video

import (
	"context"
	"fmt"
	"github.com/ACaiCat/tiktok-go/kitex_gen/common"
	"github.com/ACaiCat/tiktok-go/kitex_gen/model"
)

type FeedReq struct {
	LatestTime *string `thrift:"latest_time,1,optional" frugal:"1,optional,string" json:"latest_time,omitempty"`
}

func NewFeedReq() *FeedReq {
	return &FeedReq{}
}

func (p *FeedReq) InitDefault() {
}

var FeedReq_LatestTime_DEFAULT string

func (p *FeedReq) GetLatestTime() (v string) {
	if !p.IsSetLatestTime() {
		return FeedReq_LatestTime_DEFAULT
	}
	return *p.LatestTime
}
func (p *FeedReq) SetLatestTime(val *string) {
	p.LatestTime = val
}

func (p *FeedReq) IsSetLatestTime() bool {
	return p.LatestTime != nil
}

func (p *FeedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedReq(%+v)", *p)
}

var fieldIDToName_FeedReq = map[int16]string{
	1: "latest_time",
}

type FeedResp struct {
	Base *common.Base     `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
	Data *model.VideoList `thrift:"data,2,required" frugal:"2,required,model.VideoList" json:"data"`
}

func NewFeedResp() *FeedResp {
	return &FeedResp{}
}

func (p *FeedResp) InitDefault() {
}

var FeedResp_Base_DEFAULT *common.Base

func (p *FeedResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return FeedResp_Base_DEFAULT
	}
	return p.Base
}

var FeedResp_Data_DEFAULT *model.VideoList

func (p *FeedResp) GetData() (v *model.VideoList) {
	if !p.IsSetData() {
		return FeedResp_Data_DEFAULT
	}
	return p.Data
}
func (p *FeedResp) SetBase(val *common.Base) {
	p.Base = val
}
func (p *FeedResp) SetData(val *model.VideoList) {
	p.Data = val
}

func (p *FeedResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *FeedResp) IsSetData() bool {
	return p.Data != nil
}

func (p *FeedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedResp(%+v)", *p)
}

var fieldIDToName_FeedResp = map[int16]string{
	1: "base",
	2: "data",
}

type PublishReq struct {
	Data        []byte `thrift:"data,1,optional" frugal:"1,optional,binary" json:"data,omitempty"`
	Title       string `thrift:"title,2,required" frugal:"2,required,string" json:"title"`
	Description string `thrift:"description,3,required" frugal:"3,required,string" json:"description"`
}

func NewPublishReq() *PublishReq {
	return &PublishReq{}
}

func (p *PublishReq) InitDefault() {
}

var PublishReq_Data_DEFAULT []byte

func (p *PublishReq) GetData() (v []byte) {
	if !p.IsSetData() {
		return PublishReq_Data_DEFAULT
	}
	return p.Data
}

func (p *PublishReq) GetTitle() (v string) {
	return p.Title
}

func (p *PublishReq) GetDescription() (v string) {
	return p.Description
}
func (p *PublishReq) SetData(val []byte) {
	p.Data = val
}
func (p *PublishReq) SetTitle(val string) {
	p.Title = val
}
func (p *PublishReq) SetDescription(val string) {
	p.Description = val
}

func (p *PublishReq) IsSetData() bool {
	return p.Data != nil
}

func (p *PublishReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishReq(%+v)", *p)
}

var fieldIDToName_PublishReq = map[int16]string{
	1: "data",
	2: "title",
	3: "description",
}

type PublishResp struct {
	Base *common.Base `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
}

func NewPublishResp() *PublishResp {
	return &PublishResp{}
}

func (p *PublishResp) InitDefault() {
}

var PublishResp_Base_DEFAULT *common.Base

func (p *PublishResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return PublishResp_Base_DEFAULT
	}
	return p.Base
}
func (p *PublishResp) SetBase(val *common.Base) {
	p.Base = val
}

func (p *PublishResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *PublishResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishResp(%+v)", *p)
}

var fieldIDToName_PublishResp = map[int16]string{
	1: "base",
}

type ListReq struct {
	UserId   string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	PageNum  int32  `thrift:"page_num,2,required" frugal:"2,required,i32" json:"page_num"`
	PageSize int32  `thrift:"page_size,3,required" frugal:"3,required,i32" json:"page_size"`
}

func NewListReq() *ListReq {
	return &ListReq{}
}

func (p *ListReq) InitDefault() {
}

func (p *ListReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *ListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ListReq) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *ListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListReq(%+v)", *p)
}

var fieldIDToName_ListReq = map[int16]string{
	1: "user_id",
	2: "page_num",
	3: "page_size",
}

type ListResp struct {
	Base *common.Base              `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
	Data *model.VideoListWithTotal `thrift:"data,2,required" frugal:"2,required,model.VideoListWithTotal" json:"data"`
}

func NewListResp() *ListResp {
	return &ListResp{}
}

func (p *ListResp) InitDefault() {
}

var ListResp_Base_DEFAULT *common.Base

func (p *ListResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return ListResp_Base_DEFAULT
	}
	return p.Base
}

var ListResp_Data_DEFAULT *model.VideoListWithTotal

func (p *ListResp) GetData() (v *model.VideoListWithTotal) {
	if !p.IsSetData() {
		return ListResp_Data_DEFAULT
	}
	return p.Data
}
func (p *ListResp) SetBase(val *common.Base) {
	p.Base = val
}
func (p *ListResp) SetData(val *model.VideoListWithTotal) {
	p.Data = val
}

func (p *ListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListResp(%+v)", *p)
}

var fieldIDToName_ListResp = map[int16]string{
	1: "base",
	2: "data",
}

type PopularReq struct {
	PageNum  int32 `thrift:"page_num,1,required" frugal:"1,required,i32" json:"page_num"`
	PageSize int32 `thrift:"page_size,2,required" frugal:"2,required,i32" json:"page_size"`
}

func NewPopularReq() *PopularReq {
	return &PopularReq{}
}

func (p *PopularReq) InitDefault() {
}

func (p *PopularReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *PopularReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PopularReq) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *PopularReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PopularReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PopularReq(%+v)", *p)
}

var fieldIDToName_PopularReq = map[int16]string{
	1: "page_num",
	2: "page_size",
}

type PopularResp struct {
	Base *common.Base     `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
	Data *model.VideoList `thrift:"data,2,required" frugal:"2,required,model.VideoList" json:"data"`
}

func NewPopularResp() *PopularResp {
	return &PopularResp{}
}

func (p *PopularResp) InitDefault() {
}

var PopularResp_Base_DEFAULT *common.Base

func (p *PopularResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return PopularResp_Base_DEFAULT
	}
	return p.Base
}

var PopularResp_Data_DEFAULT *model.VideoList

func (p *PopularResp) GetData() (v *model.VideoList) {
	if !p.IsSetData() {
		return PopularResp_Data_DEFAULT
	}
	return p.Data
}
func (p *PopularResp) SetBase(val *common.Base) {
	p.Base = val
}
func (p *PopularResp) SetData(val *model.VideoList) {
	p.Data = val
}

func (p *PopularResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *PopularResp) IsSetData() bool {
	return p.Data != nil
}

func (p *PopularResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PopularResp(%+v)", *p)
}

var fieldIDToName_PopularResp = map[int16]string{
	1: "base",
	2: "data",
}

type SearchReq struct {
	Keywords string  `thrift:"keywords,1,required" frugal:"1,required,string" json:"keywords"`
	PageNum  int32   `thrift:"page_num,2,required" frugal:"2,required,i32" json:"page_num"`
	PageSize int32   `thrift:"page_size,3,required" frugal:"3,required,i32" json:"page_size"`
	FromDate *string `thrift:"from_date,4,optional" frugal:"4,optional,string" json:"from_date,omitempty"`
	ToDate   *string `thrift:"to_date,5,optional" frugal:"5,optional,string" json:"to_date,omitempty"`
	Username *string `thrift:"username,6,optional" frugal:"6,optional,string" json:"username,omitempty"`
}

func NewSearchReq() *SearchReq {
	return &SearchReq{}
}

func (p *SearchReq) InitDefault() {
}

func (p *SearchReq) GetKeywords() (v string) {
	return p.Keywords
}

func (p *SearchReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *SearchReq) GetPageSize() (v int32) {
	return p.PageSize
}

var SearchReq_FromDate_DEFAULT string

func (p *SearchReq) GetFromDate() (v string) {
	if !p.IsSetFromDate() {
		return SearchReq_FromDate_DEFAULT
	}
	return *p.FromDate
}

var SearchReq_ToDate_DEFAULT string

func (p *SearchReq) GetToDate() (v string) {
	if !p.IsSetToDate() {
		return SearchReq_ToDate_DEFAULT
	}
	return *p.ToDate
}

var SearchReq_Username_DEFAULT string

func (p *SearchReq) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return SearchReq_Username_DEFAULT
	}
	return *p.Username
}
func (p *SearchReq) SetKeywords(val string) {
	p.Keywords = val
}
func (p *SearchReq) SetPageNum(val int32) {
	p.PageNum = val
}
func (p *SearchReq) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *SearchReq) SetFromDate(val *string) {
	p.FromDate = val
}
func (p *SearchReq) SetToDate(val *string) {
	p.ToDate = val
}
func (p *SearchReq) SetUsername(val *string) {
	p.Username = val
}

func (p *SearchReq) IsSetFromDate() bool {
	return p.FromDate != nil
}

func (p *SearchReq) IsSetToDate() bool {
	return p.ToDate != nil
}

func (p *SearchReq) IsSetUsername() bool {
	return p.Username != nil
}

func (p *SearchReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchReq(%+v)", *p)
}

var fieldIDToName_SearchReq = map[int16]string{
	1: "keywords",
	2: "page_num",
	3: "page_size",
	4: "from_date",
	5: "to_date",
	6: "username",
}

type SearchResp struct {
	Base *common.Base     `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
	Data *model.VideoList `thrift:"data,2,required" frugal:"2,required,model.VideoList" json:"data"`
}

func NewSearchResp() *SearchResp {
	return &SearchResp{}
}

func (p *SearchResp) InitDefault() {
}

var SearchResp_Base_DEFAULT *common.Base

func (p *SearchResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return SearchResp_Base_DEFAULT
	}
	return p.Base
}

var SearchResp_Data_DEFAULT *model.VideoList

func (p *SearchResp) GetData() (v *model.VideoList) {
	if !p.IsSetData() {
		return SearchResp_Data_DEFAULT
	}
	return p.Data
}
func (p *SearchResp) SetBase(val *common.Base) {
	p.Base = val
}
func (p *SearchResp) SetData(val *model.VideoList) {
	p.Data = val
}

func (p *SearchResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *SearchResp) IsSetData() bool {
	return p.Data != nil
}

func (p *SearchResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchResp(%+v)", *p)
}

var fieldIDToName_SearchResp = map[int16]string{
	1: "base",
	2: "data",
}

type VisitVideoReq struct {
	VideoId string `thrift:"video_id,1,required" frugal:"1,required,string" json:"video_id"`
}

func NewVisitVideoReq() *VisitVideoReq {
	return &VisitVideoReq{}
}

func (p *VisitVideoReq) InitDefault() {
}

func (p *VisitVideoReq) GetVideoId() (v string) {
	return p.VideoId
}
func (p *VisitVideoReq) SetVideoId(val string) {
	p.VideoId = val
}

func (p *VisitVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VisitVideoReq(%+v)", *p)
}

var fieldIDToName_VisitVideoReq = map[int16]string{
	1: "video_id",
}

type VisitVideoResp struct {
	Base *common.Base `thrift:"base,1,required" frugal:"1,required,common.Base" json:"base"`
}

func NewVisitVideoResp() *VisitVideoResp {
	return &VisitVideoResp{}
}

func (p *VisitVideoResp) InitDefault() {
}

var VisitVideoResp_Base_DEFAULT *common.Base

func (p *VisitVideoResp) GetBase() (v *common.Base) {
	if !p.IsSetBase() {
		return VisitVideoResp_Base_DEFAULT
	}
	return p.Base
}
func (p *VisitVideoResp) SetBase(val *common.Base) {
	p.Base = val
}

func (p *VisitVideoResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VisitVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VisitVideoResp(%+v)", *p)
}

var fieldIDToName_VisitVideoResp = map[int16]string{
	1: "base",
}

type VideoService interface {
	Feed(ctx context.Context, req *FeedReq) (r *FeedResp, err error)

	Publish(ctx context.Context, req *PublishReq) (r *PublishResp, err error)

	List(ctx context.Context, req *ListReq) (r *ListResp, err error)

	Popular(ctx context.Context, req *PopularReq) (r *PopularResp, err error)

	Search(ctx context.Context, req *SearchReq) (r *SearchResp, err error)

	VisitVideo(ctx context.Context, req *VisitVideoReq) (r *VisitVideoResp, err error)
}

type VideoServiceFeedArgs struct {
	Req *FeedReq `thrift:"req,1" frugal:"1,default,FeedReq" json:"req"`
}

func NewVideoServiceFeedArgs() *VideoServiceFeedArgs {
	return &VideoServiceFeedArgs{}
}

func (p *VideoServiceFeedArgs) InitDefault() {
}

var VideoServiceFeedArgs_Req_DEFAULT *FeedReq

func (p *VideoServiceFeedArgs) GetReq() (v *FeedReq) {
	if !p.IsSetReq() {
		return VideoServiceFeedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceFeedArgs) SetReq(val *FeedReq) {
	p.Req = val
}

func (p *VideoServiceFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceFeedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceFeedArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceFeedArgs = map[int16]string{
	1: "req",
}

type VideoServiceFeedResult struct {
	Success *FeedResp `thrift:"success,0,optional" frugal:"0,optional,FeedResp" json:"success,omitempty"`
}

func NewVideoServiceFeedResult() *VideoServiceFeedResult {
	return &VideoServiceFeedResult{}
}

func (p *VideoServiceFeedResult) InitDefault() {
}

var VideoServiceFeedResult_Success_DEFAULT *FeedResp

func (p *VideoServiceFeedResult) GetSuccess() (v *FeedResp) {
	if !p.IsSetSuccess() {
		return VideoServiceFeedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*FeedResp)
}

func (p *VideoServiceFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceFeedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceFeedResult(%+v)", *p)
}

var fieldIDToName_VideoServiceFeedResult = map[int16]string{
	0: "success",
}

type VideoServicePublishArgs struct {
	Req *PublishReq `thrift:"req,1" frugal:"1,default,PublishReq" json:"req"`
}

func NewVideoServicePublishArgs() *VideoServicePublishArgs {
	return &VideoServicePublishArgs{}
}

func (p *VideoServicePublishArgs) InitDefault() {
}

var VideoServicePublishArgs_Req_DEFAULT *PublishReq

func (p *VideoServicePublishArgs) GetReq() (v *PublishReq) {
	if !p.IsSetReq() {
		return VideoServicePublishArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServicePublishArgs) SetReq(val *PublishReq) {
	p.Req = val
}

func (p *VideoServicePublishArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServicePublishArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePublishArgs(%+v)", *p)
}

var fieldIDToName_VideoServicePublishArgs = map[int16]string{
	1: "req",
}

type VideoServicePublishResult struct {
	Success *PublishResp `thrift:"success,0,optional" frugal:"0,optional,PublishResp" json:"success,omitempty"`
}

func NewVideoServicePublishResult() *VideoServicePublishResult {
	return &VideoServicePublishResult{}
}

func (p *VideoServicePublishResult) InitDefault() {
}

var VideoServicePublishResult_Success_DEFAULT *PublishResp

func (p *VideoServicePublishResult) GetSuccess() (v *PublishResp) {
	if !p.IsSetSuccess() {
		return VideoServicePublishResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServicePublishResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublishResp)
}

func (p *VideoServicePublishResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServicePublishResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePublishResult(%+v)", *p)
}

var fieldIDToName_VideoServicePublishResult = map[int16]string{
	0: "success",
}

type VideoServiceListArgs struct {
	Req *ListReq `thrift:"req,1" frugal:"1,default,ListReq" json:"req"`
}

func NewVideoServiceListArgs() *VideoServiceListArgs {
	return &VideoServiceListArgs{}
}

func (p *VideoServiceListArgs) InitDefault() {
}

var VideoServiceListArgs_Req_DEFAULT *ListReq

func (p *VideoServiceListArgs) GetReq() (v *ListReq) {
	if !p.IsSetReq() {
		return VideoServiceListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceListArgs) SetReq(val *ListReq) {
	p.Req = val
}

func (p *VideoServiceListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceListArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceListArgs = map[int16]string{
	1: "req",
}

type VideoServiceListResult struct {
	Success *ListResp `thrift:"success,0,optional" frugal:"0,optional,ListResp" json:"success,omitempty"`
}

func NewVideoServiceListResult() *VideoServiceListResult {
	return &VideoServiceListResult{}
}

func (p *VideoServiceListResult) InitDefault() {
}

var VideoServiceListResult_Success_DEFAULT *ListResp

func (p *VideoServiceListResult) GetSuccess() (v *ListResp) {
	if !p.IsSetSuccess() {
		return VideoServiceListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceListResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListResp)
}

func (p *VideoServiceListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceListResult(%+v)", *p)
}

var fieldIDToName_VideoServiceListResult = map[int16]string{
	0: "success",
}

type VideoServicePopularArgs struct {
	Req *PopularReq `thrift:"req,1" frugal:"1,default,PopularReq" json:"req"`
}

func NewVideoServicePopularArgs() *VideoServicePopularArgs {
	return &VideoServicePopularArgs{}
}

func (p *VideoServicePopularArgs) InitDefault() {
}

var VideoServicePopularArgs_Req_DEFAULT *PopularReq

func (p *VideoServicePopularArgs) GetReq() (v *PopularReq) {
	if !p.IsSetReq() {
		return VideoServicePopularArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServicePopularArgs) SetReq(val *PopularReq) {
	p.Req = val
}

func (p *VideoServicePopularArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServicePopularArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePopularArgs(%+v)", *p)
}

var fieldIDToName_VideoServicePopularArgs = map[int16]string{
	1: "req",
}

type VideoServicePopularResult struct {
	Success *PopularResp `thrift:"success,0,optional" frugal:"0,optional,PopularResp" json:"success,omitempty"`
}

func NewVideoServicePopularResult() *VideoServicePopularResult {
	return &VideoServicePopularResult{}
}

func (p *VideoServicePopularResult) InitDefault() {
}

var VideoServicePopularResult_Success_DEFAULT *PopularResp

func (p *VideoServicePopularResult) GetSuccess() (v *PopularResp) {
	if !p.IsSetSuccess() {
		return VideoServicePopularResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServicePopularResult) SetSuccess(x interface{}) {
	p.Success = x.(*PopularResp)
}

func (p *VideoServicePopularResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServicePopularResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServicePopularResult(%+v)", *p)
}

var fieldIDToName_VideoServicePopularResult = map[int16]string{
	0: "success",
}

type VideoServiceSearchArgs struct {
	Req *SearchReq `thrift:"req,1" frugal:"1,default,SearchReq" json:"req"`
}

func NewVideoServiceSearchArgs() *VideoServiceSearchArgs {
	return &VideoServiceSearchArgs{}
}

func (p *VideoServiceSearchArgs) InitDefault() {
}

var VideoServiceSearchArgs_Req_DEFAULT *SearchReq

func (p *VideoServiceSearchArgs) GetReq() (v *SearchReq) {
	if !p.IsSetReq() {
		return VideoServiceSearchArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceSearchArgs) SetReq(val *SearchReq) {
	p.Req = val
}

func (p *VideoServiceSearchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceSearchArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceSearchArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceSearchArgs = map[int16]string{
	1: "req",
}

type VideoServiceSearchResult struct {
	Success *SearchResp `thrift:"success,0,optional" frugal:"0,optional,SearchResp" json:"success,omitempty"`
}

func NewVideoServiceSearchResult() *VideoServiceSearchResult {
	return &VideoServiceSearchResult{}
}

func (p *VideoServiceSearchResult) InitDefault() {
}

var VideoServiceSearchResult_Success_DEFAULT *SearchResp

func (p *VideoServiceSearchResult) GetSuccess() (v *SearchResp) {
	if !p.IsSetSuccess() {
		return VideoServiceSearchResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceSearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchResp)
}

func (p *VideoServiceSearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceSearchResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceSearchResult(%+v)", *p)
}

var fieldIDToName_VideoServiceSearchResult = map[int16]string{
	0: "success",
}

type VideoServiceVisitVideoArgs struct {
	Req *VisitVideoReq `thrift:"req,1" frugal:"1,default,VisitVideoReq" json:"req"`
}

func NewVideoServiceVisitVideoArgs() *VideoServiceVisitVideoArgs {
	return &VideoServiceVisitVideoArgs{}
}

func (p *VideoServiceVisitVideoArgs) InitDefault() {
}

var VideoServiceVisitVideoArgs_Req_DEFAULT *VisitVideoReq

func (p *VideoServiceVisitVideoArgs) GetReq() (v *VisitVideoReq) {
	if !p.IsSetReq() {
		return VideoServiceVisitVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceVisitVideoArgs) SetReq(val *VisitVideoReq) {
	p.Req = val
}

func (p *VideoServiceVisitVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceVisitVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceVisitVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceVisitVideoArgs = map[int16]string{
	1: "req",
}

type VideoServiceVisitVideoResult struct {
	Success *VisitVideoResp `thrift:"success,0,optional" frugal:"0,optional,VisitVideoResp" json:"success,omitempty"`
}

func NewVideoServiceVisitVideoResult() *VideoServiceVisitVideoResult {
	return &VideoServiceVisitVideoResult{}
}

func (p *VideoServiceVisitVideoResult) InitDefault() {
}

var VideoServiceVisitVideoResult_Success_DEFAULT *VisitVideoResp

func (p *VideoServiceVisitVideoResult) GetSuccess() (v *VisitVideoResp) {
	if !p.IsSetSuccess() {
		return VideoServiceVisitVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceVisitVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*VisitVideoResp)
}

func (p *VideoServiceVisitVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceVisitVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceVisitVideoResult(%+v)", *p)
}

var fieldIDToName_VideoServiceVisitVideoResult = map[int16]string{
	0: "success",
}
