// Code generated by hertz generator.

package video

import (
	"context"

	video "github.com/ACaiCat/tiktok-go/biz/model/video"
	mw "github.com/ACaiCat/tiktok-go/biz/mw/auth"
	"github.com/ACaiCat/tiktok-go/biz/pack"
	service "github.com/ACaiCat/tiktok-go/biz/service/video"
	"github.com/ACaiCat/tiktok-go/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router /video/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.FeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	videos, err := service.NewVideoService().GetFeed(&req)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespFeedList(c, videos)
}

// Publish .
// @router /video/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := mw.GetUserID(c)
	fileHeader, err := c.FormFile("data")
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		return
	}

	err = service.NewVideoService().PublishVideo(userID, req.Title, req.Description, fileHeader)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespPublish(c)
}

// List .
// @router /video/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	videos, total, err := service.NewVideoService().GetVideoList(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespVideoList(c, videos, total)
}

// Popular .
// @router /video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	videos, err := service.NewVideoService().GetPopularVideos(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespPopularList(c, videos)

}

// Search .
// @router /video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	videos, err := service.NewVideoService().SearchVideo(&req)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSearch(c, videos)
}
