// Code generated by hertz generator.

package video

import (
	"context"

	video "github.com/ACaiCat/tiktok-go/biz/model/video"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router /video/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.FeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.FeedResp)

	c.JSON(consts.StatusOK, resp)
}

// Publish .
// @router /video/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishResp)

	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /video/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.ListResp)

	c.JSON(consts.StatusOK, resp)
}

// Popular .
// @router /video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PopularResp)

	c.JSON(consts.StatusOK, resp)
}

// Search .
// @router /video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchResp)

	c.JSON(consts.StatusOK, resp)
}
