// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/ACaiCat/tiktok-go/biz/model/tiktok-go/user"
	"github.com/ACaiCat/tiktok-go/biz/pack"
	service "github.com/ACaiCat/tiktok-go/biz/service/user"
	"github.com/ACaiCat/tiktok-go/pkg/constants"
	"github.com/ACaiCat/tiktok-go/pkg/errno"
	"github.com/ACaiCat/tiktok-go/pkg/jwt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = service.NewUserService().UserRegister(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	pack.RespRegister(c)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	usr, accessToken, refreshToken, err := service.NewUserService().UserLogin(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}

	c.Header(constants.AccessTokenHeader, accessToken)
	c.Header(constants.RefreshTokenHeader, refreshToken)

	pack.RespLogin(c, usr)
}

// Refresh .
// @router /auth/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RefreshReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, err := jwt.VerifyToken(req.RefreshToken, constants.TypeRefreshToken)
	if err != nil {
		pack.RespError(c, err)
		return
	}

	accessToken, err := jwt.CreateToken(constants.TypeAccessToken, userID)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	refreshToken, err := jwt.CreateToken(constants.TypeRefreshToken, userID)

	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespRefreshToken(c, accessToken, refreshToken)
}

// Info .
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LoginResp)

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UploadAvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UploadAvatarResp)

	c.JSON(consts.StatusOK, resp)
}

// MFAQRCode .
// @router /auth/mfa/qrcode [GET]
func MFAQRCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFAQRCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.MFAQRCodeResp)

	resp.Data = &user.MFAQRCodeData{
		Secret: "",
		Qrcode: "",
	}

	c.JSON(consts.StatusOK, resp)
}

// BindMFA .
// @router /auth/mfa/bind [POST]
func BindMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.BindMFAReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.MFAQRCodeResp)

	c.JSON(consts.StatusOK, resp)
}

// SearchImage .
// @router /user/image/search [POST]
func SearchImage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SearchImageReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamErr.WithError(err))
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.SearchImageResp)

	c.JSON(consts.StatusOK, resp)
}
