// Code generated by Kitex v0.16.1. DO NOT EDIT.

package socialservice

import (
	"context"
	social "github.com/ACaiCat/tiktok-go/kitex_gen/social"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Follow(ctx context.Context, req *social.FollowReq, callOptions ...callopt.Option) (r *social.FollowResp, err error)
	ListFollowing(ctx context.Context, req *social.ListFollowingReq, callOptions ...callopt.Option) (r *social.ListFollowingResp, err error)
	ListFollower(ctx context.Context, req *social.ListFollowerReq, callOptions ...callopt.Option) (r *social.ListFollowerResp, err error)
	ListFriend(ctx context.Context, req *social.ListFriendReq, callOptions ...callopt.Option) (r *social.ListFriendResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) Follow(ctx context.Context, req *social.FollowReq, callOptions ...callopt.Option) (r *social.FollowResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Follow(ctx, req)
}

func (p *kSocialServiceClient) ListFollowing(ctx context.Context, req *social.ListFollowingReq, callOptions ...callopt.Option) (r *social.ListFollowingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFollowing(ctx, req)
}

func (p *kSocialServiceClient) ListFollower(ctx context.Context, req *social.ListFollowerReq, callOptions ...callopt.Option) (r *social.ListFollowerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFollower(ctx, req)
}

func (p *kSocialServiceClient) ListFriend(ctx context.Context, req *social.ListFriendReq, callOptions ...callopt.Option) (r *social.ListFriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriend(ctx, req)
}
