// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatMessage = "chat_messages"

// ChatMessage mapped from table <chat_messages>
type ChatMessage struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:消息ID" json:"id"`                      // 消息ID
	SenderID   int64      `gorm:"column:sender_id;not null;comment:发送者ID" json:"sender_id"`                            // 发送者ID
	ReceiverID int64      `gorm:"column:receiver_id;not null;comment:接收者ID" json:"receiver_id"`                        // 接收者ID
	Content    string     `gorm:"column:content;not null;comment:消息内容" json:"content"`                                 // 消息内容
	ReadAt     *time.Time `gorm:"column:read_at;comment:阅读时间" json:"read_at"`                                          // 阅读时间
	IsAi       bool       `gorm:"column:is_ai;not null;comment:是否为AI的消息" json:"is_ai"`                                 // 是否为AI的消息
	CreatedAt  time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName ChatMessage's table name
func (*ChatMessage) TableName() string {
	return TableNameChatMessage
}
