// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFollower = "followers"

// Follower mapped from table <followers>
type Follower struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:关注ID" json:"id"`                      // 关注ID
	UserID     int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	FollowerID int64     `gorm:"column:follower_id;not null;comment:粉丝ID" json:"follower_id"`                         // 粉丝ID
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName Follower's table name
func (*Follower) TableName() string {
	return TableNameFollower
}
